### ISSUE TITLE
⚡ Nollning 2023

### ISSUE THREAD

**Issue by danieladugyan** [Dsek-LTH/member-page#1128]
There will be 2 versions of the dsek.se/nolla webpage. One is live now and will be shown up until 23 august. Following that a new version will be deployed with a theme that matches this year's nollningstheme. Most of the content will be the same but the design will change quite a lot.

Since this is a temporary page focus lies in getting the features out quickly. Avoid unnecessary abstractions and prefer code duplication (within reason).

Figma: https://www.figma.com/file/HEGAVFbtdEO4qeK5GYj9Zx/Nollningen-2023?type=design&node-id=7%3A3&mode=dev
(sign in and request access or send your email address to @danieladugyan)

**Important!** Make sure to assign yourself to issues before starting, otherwise someone else might end up working on the same thing!
```[tasklist]
### Stories (post-reveal)
- [x] ✨ Implement post-reveal theme/layout
- [ ] https://github.com/Dsek-LTH/member-page/issues/1193
- [ ] 💬 Add FAQ cards
- [ ] ✨ Add dance movie
- [ ] ✨ Add reveal movie
- [ ] https://github.com/Dsek-LTH/member-page/issues/1208
```
```[tasklist]
### Stories
- [x] 🐛 Scroll up is still broken
- [x] 🐛 Fix marginTop on main index
- [x] 🐛 Fix marginTop on nolla events
- [x] 🌐 Handle translations for calendar events
- [x] 💬 Add contact info for Trivsel
- [x] 🐛 Fix nolla news notification link
- [x] 🐛 Fix potential light mode issues
- [x] 🐛 Add missing nolla footer translation
- [x] Finish up news page, change mandate names
- [x] Update pepper images
- [x] Add additional tags to applicable events (food/pub/sit)
- [ ] https://github.com/Dsek-LTH/member-page/issues/1220
- [ ] https://github.com/Dsek-LTH/member-page/issues/1218
- [x] https://github.com/Dsek-LTH/member-page/issues/1217
- [ ] #1124
- [x] Add image captions to housing page
- [x] Fix image overflow on housing page
- [x] Add a link to https://www.student.lth.se/ny-student/ on registration page
- [x] 🪲 Remove D-guild logo from guild page
- [x] Fix Stina's description on pepper page
- [x] Add nollning tag to default notifications
- [x] Downgrade PGAdmin (with next release)
- [ ] https://github.com/Dsek-LTH/member-page/issues/1186
- [ ] https://github.com/Dsek-LTH/member-page/issues/1187
- [ ] https://github.com/Dsek-LTH/member-page/issues/1201
- [ ] #1048
- [ ] #1118
```
```[tasklist]
### Extras
- [ ] ✨ Add an interactive 3D map of campus
- [ ] ✨ Handle sales of free items through the shop (i.e patches)
- [ ] ✨ Link to phaddergroup instagram accounts
- [ ] ✨ Add a leaderboard tracking points for Pepparuppdrag
- [ ] ✨ Add a component showing weekly Pepparuppdrag
```
