### ISSUE TITLE
Add nolla calendar

### ISSUE THREAD

**Issue by danieladugyan** [Dsek-LTH/member-page#1217]
```[tasklist]
### Tasks
- [ ] https://github.com/Dsek-LTH/member-page/issues/1189
- [x] Make it possible to subscribe to calendar
- [ ] https://github.com/Dsek-LTH/member-page/issues/1214
- [ ] https://github.com/Dsek-LTH/member-page/issues/1190
```
