### ISSUE TITLE
✨ Add nolla pages to app

### ISSUE THREAD

**Issue by danieladugyan** [Dsek-LTH/member-page#1218]
```[tasklist]
### Tasks
- [x] Add a link to nolla section of app
- [x] Extend session duration
- [ ] Redirect nolla accounts to nolla index page?
- [ ] Disable signIn on session expiration?
```
